version: "3.9"
services:
  urlshortener:
    build: .
    ports:
      - 38744:38744
    environment:
      - REDIS_ADDRESS=cache:6379
      - DATABASE_DSN=test:test@tcp(database:3306)/short_url?charset=utf8&parseTime=True&loc=Local
      - GIN_MODE=release
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy

  database:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: short_url
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


  cache:
    image: redis
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30