httpServer:
  domain: localhost
  port: 38744

database:
  dsn: "test:test@tcp(localhost:3306)/short_url?charset=utf8&parseTime=True&loc=Local"

redis:
  address: "localhost:6379"
  dialTimeout: 10s
  expiration: 6h

logger:
  level: -1

service:
  limitRate: 60
  burstSize: 60